
#' Read ICP-MS data files generated by the Thermo Scientific iCAP-RQ
#'
#' @param path Path to stored ICP-MS files
#' @param sheet_name Name of MS Excel sheet where data are stored
#' @param first_line The first column matches this pattern at the first line of data.
#' As an input to `stringr::str_detect()`, this can be a partial match or a regex.
#'
#' @return A tibble with columns `sample_name`, `category`, `isotope`, `element`,
#' `value`, and `unit`
#' @importFrom tibble as_tibble
#' @importFrom dplyr mutate filter select slice summarize across select_at transmute vars %>%
#' @importFrom stringr str_detect str_extract str_replace str_to_title
#' @importFrom tidyr replace_na pivot_longer fill
#' @importFrom tidyselect everything starts_with
#' @importFrom rlang set_names .data
#' @importFrom janitor clean_names
#' @importFrom readxl read_excel
#' @export
#'
#' @examples
#' file <- list.files(
#'    path = system.file("extdata", package = "cwrshelpr"),
#'    full.names = TRUE,
#'    pattern = ".+\\.xlsx"
#' )
#' read_icp(file[1])
read_icp <- function(
  path,
  sheet_name = "Dilution factor included",
  first_line = "Sample List"
) {
  path %>%
    read_excel(col_names = FALSE, sheet = sheet_name) %>%
    # next 8 lines filter out rows before the data starts:
    mutate(
      start_indicator_var = str_detect(.data$`...1`, first_line) %>%
        replace_na(0) %>%
        cumsum() %>%
        as.logical()
    ) %>%
    filter(.data$start_indicator_var) %>%
    select(-.data$start_indicator_var) %>%
    t() %>%
    as_tibble(.name_repair = "unique") %>%
    fill(.data$`...1`) %>%
    t() %>%
    as_tibble(.name_repair = "unique") %>%
    two_row_names() %>%
    slice(-(1:2)) %>%
    clean_names() %>%
    select_at(
      vars(c(
          .data$sample_list_label,
          .data$sample_list_category,
          starts_with("x")
        ))
    ) %>%
    pivot_longer(
      -c(.data$sample_list_label, .data$sample_list_category),
      names_to = c("element", ".value"),
      names_pattern = "(.+ked_)(.+)"
    ) %>%
    transmute(
      sample_name = .data$sample_list_label,
      estimate_type = .data$sample_list_category,
      isotope = str_extract(.data$element, "\\d+"),
      element = str_replace(.data$element, "(x\\d+)([a-z]+)(.+)", "\\2") %>%
        str_to_title(),
      value = as.numeric(.data$value),
      unit = .data$unit
    )
}

two_row_names <- function(x) {
  x %>%
    set_names(
      nm = slice(x, 1:2) %>%
        summarize(across(everything(), ~ paste(.x, collapse = "_")))
    )
}
