
#' Read ICP-MS data files generated by the Thermo Scientific iCAP-RQ
#'
#' @param path Path to stored ICP-MS files
#' @param sheet_name Name of MS Excel sheet where data are stored
#' @param first_line The first column matches this pattern at the first line of data.
#' As an input to `stringr::str_detect()`, this can be a partial match or a regex.
#'
#' @return
#' @importFrom tibble as_tibble
#' @importFrom dplyr mutate filter select fill slice summarize across select_at transmute
#' @importFrom stringr str_detect str_extract str_replace str_to_title
#' @importFrom tidyr replace_na pivot_longer
#' @importFrom tidyselect everything vars starts_with
#' @importFrom rlang set_names .data
#' @importFrom janitor clean_names
#' @export
#'
#' @examples
read_icp <- function(
  path,
  sheet_name = "Dilution factor included",
  first_line = "Sample List"
) {
  path %>%
    read_excel(col_names = FALSE, sheet = sheet_name) %>%
    # next 8 lines filter out rows before the data starts:
    mutate(
      start_indicator_var = str_detect(`...1`, first_line) %>%
        replace_na(0) %>%
        cumsum() %>%
        as.logical()
    ) %>%
    filter(start_indicator_var) %>%
    select(-start_indicator_var) %>%
    t() %>%
    as_tibble(.name_repair = "unique") %>%
    fill(`...1`) %>%
    t() %>%
    as_tibble(.name_repair = "unique") %>%
    set_names(
      nm = slice(., 1:2) %>%
        summarize(across(everything(), ~ paste(.x, collapse = "_")))
    ) %>%
    slice(-(1:2)) %>%
    clean_names() %>%
    select_at(vars(c(sample_list_label, sample_list_category, starts_with("x")))) %>%
    pivot_longer(
      -c(sample_list_label, sample_list_category),
      names_to = c("element", ".value"),
      names_pattern = "(.+ked_)(.+)"
    ) %>%
    transmute(
      sample_name = sample_list_label,
      category = sample_list_category,
      isotope = str_extract(element, "\\d+"),
      element = str_replace(element, "(x\\d+)([a-z]+)(.+)", "\\2") %>%
        str_to_title(),
      value = as.numeric(value),
      unit
    )
}
